/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;

/**
 *
 * @author Meidiana Dwi P
 */
public class hapusdata extends javax.swing.JFrame {

    /**
     * Creates new form hapusdata
     */
    public hapusdata() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        hapusDokter = new javax.swing.JButton();
        hapusPasien = new javax.swing.JButton();
        hapusRuangan = new javax.swing.JButton();
        hapusInap = new javax.swing.JButton();
        hapusDiagnosa = new javax.swing.JButton();
        Kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hapus Data");

        hapusDokter.setText("Hapus Data Dokter");
        hapusDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusDokterActionPerformed(evt);
            }
        });

        hapusPasien.setText("Hapus Data Pasien");

        hapusRuangan.setText("Hapus Data Ruangan");

        hapusInap.setText("Hapus Data Pasien Inap");

        hapusDiagnosa.setText("Hapus Data Diagnosa");

        Kembali.setText("Kembali");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(176, 176, 176))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hapusInap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hapusRuangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hapusPasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hapusDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hapusDiagnosa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Kembali)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(hapusDokter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hapusPasien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hapusRuangan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hapusInap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hapusDiagnosa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Kembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hapusDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusDokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusDokterActionPerformed

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hapusdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hapusdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hapusdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hapusdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hapusdata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Kembali;
    private javax.swing.JButton hapusDiagnosa;
    private javax.swing.JButton hapusDokter;
    private javax.swing.JButton hapusInap;
    private javax.swing.JButton hapusPasien;
    private javax.swing.JButton hapusRuangan;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the Kembali
     */
    public javax.swing.JButton getKembali() {
        return Kembali;
    }

    /**
     * @param Kembali the Kembali to set
     */
    public void setKembali(javax.swing.JButton Kembali) {
        this.Kembali = Kembali;
    }

    /**
     * @return the hapusDiagnosa
     */
    public javax.swing.JButton getHapusDiagnosa() {
        return hapusDiagnosa;
    }

    /**
     * @param hapusDiagnosa the hapusDiagnosa to set
     */
    public void setHapusDiagnosa(javax.swing.JButton hapusDiagnosa) {
        this.hapusDiagnosa = hapusDiagnosa;
    }

    /**
     * @return the hapusDokter
     */
    public javax.swing.JButton getHapusDokter() {
        return hapusDokter;
    }

    /**
     * @param hapusDokter the hapusDokter to set
     */
    public void setHapusDokter(javax.swing.JButton hapusDokter) {
        this.hapusDokter = hapusDokter;
    }

    /**
     * @return the hapusInap
     */
    public javax.swing.JButton getHapusInap() {
        return hapusInap;
    }

    /**
     * @param hapusInap the hapusInap to set
     */
    public void setHapusInap(javax.swing.JButton hapusInap) {
        this.hapusInap = hapusInap;
    }

    /**
     * @return the hapusPasien
     */
    public javax.swing.JButton getHapusPasien() {
        return hapusPasien;
    }

    /**
     * @param hapusPasien the hapusPasien to set
     */
    public void setHapusPasien(javax.swing.JButton hapusPasien) {
        this.hapusPasien = hapusPasien;
    }

    /**
     * @return the hapusRuangan
     */
    public javax.swing.JButton getHapusRuangan() {
        return hapusRuangan;
    }

    /**
     * @param hapusRuangan the hapusRuangan to set
     */
    public void setHapusRuangan(javax.swing.JButton hapusRuangan) {
        this.hapusRuangan = hapusRuangan;
    }
    
    public void addListener (ActionListener al) {
        hapusDokter.addActionListener(al);
        hapusDiagnosa.addActionListener(al);
        hapusInap.addActionListener(al);
        hapusPasien.addActionListener(al);
        hapusRuangan.addActionListener(al);
        Kembali.addActionListener(al);
    }
}
