/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;

/**
 *
 * @author Meidiana Dwi P
 */
public class lihatdata extends javax.swing.JFrame {

    /**
     * Creates new form lihatdata
     */
    public lihatdata() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lihatDokter = new javax.swing.JButton();
        lihatPasien = new javax.swing.JButton();
        lihatRuangan = new javax.swing.JButton();
        kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Lihat Data");

        lihatDokter.setText("Lihat data dokter");

        lihatPasien.setText("Lihat data pasien");

        lihatRuangan.setText("Lihat data ruangan");

        kembali.setText("Kembali");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lihatRuangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lihatPasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lihatDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kembali)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(lihatDokter)
                .addGap(12, 12, 12)
                .addComponent(lihatPasien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lihatRuangan)
                .addGap(61, 61, 61)
                .addComponent(kembali)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lihatdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lihatdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lihatdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lihatdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lihatdata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton kembali;
    private javax.swing.JButton lihatDokter;
    private javax.swing.JButton lihatPasien;
    private javax.swing.JButton lihatRuangan;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the kembali
     */
    public javax.swing.JButton getKembali() {
        return kembali;
    }

    /**
     * @param kembali the kembali to set
     */
    public void setKembali(javax.swing.JButton kembali) {
        this.kembali = kembali;
    }

    /**
     * @return the lihatDokter
     */
    public javax.swing.JButton getLihatDokter() {
        return lihatDokter;
    }

    /**
     * @param lihatDokter the lihatDokter to set
     */
    public void setLihatDokter(javax.swing.JButton lihatDokter) {
        this.lihatDokter = lihatDokter;
    }

    /**
     * @return the lihatPasien
     */
    public javax.swing.JButton getLihatPasien() {
        return lihatPasien;
    }

    /**
     * @param lihatPasien the lihatPasien to set
     */
    public void setLihatPasien(javax.swing.JButton lihatPasien) {
        this.lihatPasien = lihatPasien;
    }

    /**
     * @return the lihatRuangan
     */
    public javax.swing.JButton getLihatRuangan() {
        return lihatRuangan;
    }

    /**
     * @param lihatRuangan the lihatRuangan to set
     */
    public void setLihatRuangan(javax.swing.JButton lihatRuangan) {
        this.lihatRuangan = lihatRuangan;
    }
    
    public void addListener(ActionListener al) {
        lihatDokter.addActionListener(al);
        lihatPasien.addActionListener(al);
        lihatRuangan.addActionListener(al);
        kembali.addActionListener(al);
    }
}
